version: 2
jobs:
  build:
    docker:
      - image: alexkrauss/isabelle-dev:latest

    steps:
      - checkout

      - restore_cache:
          key: v1-Isabelle-{{ checksum "ISABELLE_VERSION" }}-{{ checksum ".circleci/prepare_isabelle.sh" }}

      - run:
          name: Prepare Isabelle
          command: .circleci/prepare_isabelle.sh

      - run:
          name: Build base image
          command: ~/Isabelle/bin/isabelle build -vb HOL-Number_Theory

      - save_cache:
          key: v1-Isabelle-{{ checksum "ISABELLE_VERSION" }}-{{ checksum ".circleci/prepare_isabelle.sh" }}
          paths:
            - ~/.isabelle
            - ~/Isabelle

      - run:
          name: Build theories
          command: ~/Isabelle/bin/isabelle build -vD .
