version: 2
jobs:
  build:
    docker:
      - image: makarius/isabelle:Isabelle2018

    steps:
      - checkout

      - run:
          name: Build base image
          command: ~/Isabelle/bin/isabelle build -vb HOL-Number_Theory

          - run:
          name: Build theories
          command: ~/Isabelle/bin/isabelle build -vD .
