name: Build Isabelle/Set
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Isabelle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.isabelle
            ~/Isabelle
            ~/AFP/thys
          key: v1-Isabelle-${{ hashFiles('ISABELLE_VERSION') }}-${{ hashFiles('AFP_VERSION') }}-${{ hashFiles('.github/workflows/prepare_isabelle.sh') }}
          restore-keys: v3-Isabelle-

      - name: Prepare Isabelle
        run: $GITHUB_WORKSPACE/.github/workflows/prepare_isabelle.sh
        shell: bash

      - name: Build base image
        run: ~/Isabelle/bin/isabelle build -vbRD .

      - name: Build theories
        run: ~/Isabelle/bin/isabelle build -vD .
